# Generated by Django 5.0.3 on 2024-04-17 00:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icao24', models.CharField(max_length=200)),
                ('firstSeen', models.IntegerField()),
                ('estDepartureAirport', models.CharField(max_length=10)),
                ('lastSeen', models.IntegerField()),
                ('estArrivalAirport', models.CharField(max_length=10)),
                ('callsign', models.CharField(max_length=8)),
                ('estDepartureAirportHorizDistance', models.IntegerField()),
                ('estDepartureAirportVertDistance', models.IntegerField()),
                ('estArrivalAirportHorizDistance', models.IntegerField()),
                ('estArrivalAirportVertDistance', models.IntegerField()),
                ('departureAirportCandidatesCount', models.IntegerField()),
                ('arrivalAirportCandidatesCount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_location', models.CharField(max_length=200)),
                ('departure_location_latitude', models.DecimalField(decimal_places=10, max_digits=200)),
                ('departure_location_longitude', models.DecimalField(decimal_places=10, max_digits=200)),
                ('layover_location', models.CharField(max_length=200)),
                ('layover_location_latitude', models.DecimalField(decimal_places=10, max_digits=200)),
                ('layover_location_longitude', models.DecimalField(decimal_places=10, max_digits=200)),
                ('arrival_location', models.CharField(max_length=200)),
                ('arrival_location_latitude', models.DecimalField(decimal_places=10, max_digits=200)),
                ('arrival_location_longitude', models.DecimalField(decimal_places=10, max_digits=200)),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('price', models.PositiveIntegerField()),
                ('seat_number', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
